# Generated by Django 5.2.8 on 2026-01-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
