# Generated by Django 5.2.8 on 2026-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_has_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
