# Generated by Django 5.2.8 on 2026-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
